SELECT * FROM CLIENTES_NEPTUNO; 
SELECT IDCLIENTE, NOMBRECOMPANIA, concat(DIRECCION, ' - ', CIUDAD, ' - ', PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;


SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT_WS(' - ', DIRECCION, CIUDAD, PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;


SELECT IDCLIENTE, UPPER(NOMBRECOMPANIA) AS EMPRESA, CONCAT_WS(' - ', DIRECCION, CIUDAD, PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;


SELECT LOWER(IDCLIENTE) AS CODIGO, UPPER(NOMBRECOMPANIA) AS EMPRESA, CONCAT_WS(' - ', DIRECCION, CIUDAD, PAIS) AS UBICACION FROM CLIENTES_NEPTUNO;


SELECT * FROM NACIMIENTOS;
SELECT FECHA, LEFT(SEXO, 1) AS SEXO, LEFT(TIPO_PARTO, 1) AS TIPO FROM NACIMIENTOS;


SELECT * FROM CLIENTES_NEPTUNO; 
SELECT *, UPPER(CONCAT(LEFT(CIUDAD, 1), LEFT(PAIS, 1), RIGHT(PAIS, 2))) AS CODIGO FROM CLIENTES_NEPTUNO;


SELECT * FROM NACIMIENTOS;
SELECT *, COUNT(SEXO) AS COUNTT FROM NACIMIENTOS;
SELECT SEXO, FECHA, TIPO_PARTO, ATENC_PART, LOCAL_PART, SUBSTRING(FECHA, 4, 2) AS MES FROM NACIMIENTOS ORDER BY MES;

SELECT SEXO, FECHA, TIPO_PARTO, REPLACE(NACIONALIDAD, 'Chilena', 'Ciudadana') AS NACIONALIDAD FROM NACIMIENTOS;



SELECT * FROM CLIENTES_NEPTUNO; 
SELECT * FROM PEDIDOS_NEPTUNO WHERE YEAR(FECHAPEDIDO) = 1998;


SELECT * FROM PEDIDOS_NEPTUNO; 
SELECT * FROM PEDIDOS_NEPTUNO WHERE MONTH(FECHAPEDIDO) BETWEEN 8 AND 9 AND YEAR(FECHAPEDIDO) = 1997;


SELECT * FROM PEDIDOS_NEPTUNO WHERE DAY(FECHAPEDIDO) = 1;


SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS' FROM PEDIDOS_NEPTUNO;


SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS', DAYNAME(FECHAPEDIDO) AS DIA FROM PEDIDOS_NEPTUNO;


SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS', DAYNAME(FECHAPEDIDO) AS DIA, 
DAYOFYEAR(FECHAPEDIDO) AS 'DIA DEL AÑO' FROM PEDIDOS_NEPTUNO;


SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS', DAYNAME(FECHAPEDIDO) AS DIA, DAYOFYEAR(FECHAPEDIDO) AS 'DIA DEL AÑO',
MONTHNAME(FECHAPEDIDO) AS 'MES' FROM PEDIDOS_NEPTUNO;


SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS', DAYNAME(FECHAPEDIDO) AS DIA, DAYOFYEAR(FECHAPEDIDO) AS 'DIA DEL AÑO',
MONTHNAME(FECHAPEDIDO) AS 'MES', ADDDATE(FECHAPEDIDO, INTERVAL 30 DAY) AS 'PRIMER VENCIMIENTO' FROM PEDIDOS_NEPTUNO;


SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS', DAYNAME(FECHAPEDIDO) AS DIA, DAYOFYEAR(FECHAPEDIDO) AS 'DIA DEL AÑO',
MONTHNAME(FECHAPEDIDO) AS 'MES', ADDDATE(FECHAPEDIDO, INTERVAL 30 DAY) AS 'PRIMER VENCIMIENTO', ADDDATE(FECHAPEDIDO, INTERVAL 2 MONTH) AS 'SEGUNDO VENCIMIENTO'
FROM PEDIDOS_NEPTUNO;



SELECT *, ROUND(CARGO * 0.21, 2) AS IVA FROM PEDIDOS_NEPTUNO;


SELECT *, ROUND(CARGO * 0.21, 2) AS IVA, ROUND(CARGO * 1.21, 2) AS NETO FROM PEDIDOS_NEPTUNO;


SELECT *, ROUND(CARGO * 0.21, 2) AS IVA, ROUND(CARGO * 1.21, 2) AS NETO, FLOOR(ROUND(CARGO * 1.21, 2)) AS 'REDONDEO A FAVOR CLIENTE'
FROM PEDIDOS_NEPTUNO;


SELECT *, ROUND(CARGO * 0.21, 2) AS IVA, ROUND(CARGO * 1.21, 2) AS NETO, FLOOR(ROUND(CARGO * 1.21, 2)) AS 'REDONDEO A FAVOR CLIENTE',
CEIL(ROUND(CARGO * 1.21, 2)) AS 'REDONDEO A FAVOR EMPRESA' FROM PEDIDOS_NEPTUNO;



SELECT *, COUNT(*) FROM PEDIDOS_NEPTUNO;


SELECT COUNT(TRANSPORTISTA) AS 'ENTREGAS SPEEDY EXPRESS';
SELECT * FROM PEDIDOS_NEPTUNO WHERE TRANSPORTISTA = 'SPEEDY EXPRESS';


SELECT COUNT(EMPLEADO) VENTAS FROM PEDIDOS_NEPTUNO WHERE EMPLEADO LIKE 'C%';


SELECT ROUND(AVG(PRECIOUNIDAD), 2) 'PRECIO PROMEDIO' FROM PRODUCTOS_NEPTUNO;


SELECT ROUND(AVG(PRECIOUNIDAD), 2) 'PRECIO PROMEDIO', MIN(PRECIOUNIDAD) 'PRECIO MINIMO' FROM PRODUCTOS_NEPTUNO;


SELECT ROUND(AVG(PRECIOUNIDAD), 2) 'PRECIO PROMEDIO', MIN(PRECIOUNIDAD) 'PRECIO MINIMO', MAX(PRECIOUNIDAD) 'PRECIO MAXIMO' FROM PRODUCTOS_NEPTUNO;


SELECT NOMBRECATEGORIA AS CATEGORIA, MAX(PRECIOUNIDAD) AS 'PRECIO MAXIMO' FROM PRODUCTOS_NEPTUNO GROUP BY CATEGORIA;


SELECT TRANSPORTISTA, COUNT(IDPEDIDO) AS ENTREGAS FROM PEDIDOS_NEPTUNO GROUP BY TRANSPORTISTA;


SELECT SEXO, COUNT(SEXO) AS NACIMIENTOS FROM NACIMIENTOS GROUP BY SEXO;


SELECT NOMBRECOMPANIA AS CLIENTE, ROUND(SUM(CARGO), 2) AS 'TOTAL GASTOS' FROM PEDIDOS_NEPTUNO GROUP BY CLIENTE;


SELECT SECCION, COUNT(SECCION) AS CANTIDAD FROM PRODUCTOS GROUP BY SECCION ORDER BY CANTIDAD DESC;


SELECT EMPLEADO, ROUND(SUM(CARGO), 2) AS FACTURACION, ROUND(AVG(CARGO), 2) AS PROMEDIO, MAX(CARGO) AS 'MEJOR VENTA',
MIN(CARGO) AS 'PEOR VENTA', COUNT(CARGO) AS VENTAS FROM PEDIDOS_NEPTUNO GROUP BY EMPLEADO;